### ISSUE TITLE
Trinea的订阅源有问题

### ISSUE THREAD

**Issue by Lee-swifter** [Gracker/Rss-IT#12]
第八个： Trinea 
网站 : trinea.cn 
Rss地址 : http://feed.feedsky.com/trinea

我在Foxmail无法添加该订阅；而且在Inoreader中显示这个订阅源有问题，无法抓取内容。
而且网站也打不开。

**Comment by Gracker** [comment]
确实是这样，我向Trinea反馈一下

**Comment by zddewe** [comment]
@Gracker 求更新Reeder备份的OPML文件
